### ISSUE TITLE
Forbidden path outside the build context

### ISSUE THREAD

**Issue by devarchi33** [lfuelling/generator-springboot-kickstart#1]
(please understand my english is poor...)

Thanks to nice project!

When running docker-compose build, I have some problem.
That is "failed to build: Forbidden path outside the build context: ../target/myapp-0.0.1-SNAPSHOT.jar"
But I don't understand because "../target/myapp-0.0.1-SNAPSHOT.jar" file exists in right path.

please give me a some tip.

**Comment by lfuelling** [comment]
Oh right sorry for that.

The 'build context' in Docker is the folder where the Dockerfiles are (or where you execute the docker command) with all subdirectories.

You can save this as a script in the root of your project:

```
#!/bin/bash
cp target/*.jar docker/
docker-compose build
```

This will copy the jar into the docker context. You just need to change the Dockerfile to point to the right location.

Hope that helps.

**Comment by lfuelling** [comment]
(I will fix this when I have time)

**Comment by skyfly33** [comment]
Ah ha!!
To run docker-compose, *.jar file, application.properties and development.pkcs12 are there in docker folder.

Refer to your comment, I copy three file to docker folder.
and I fix Docker file.

It works well! Thank really big help to me 👍

**Comment by lfuelling** [comment]
No problem. 

I'll repoen this issue to close it in a commit in the weekend.
